export default {
    "id": "",
    "user_role": "",
    "state": "",
    "accepted_tos": "",
    "zip_code": "",
    "license_type": "",
    "license_number": "",
    "given_name": "",
    "family_name": "",
    "profile_photo_url": "",
    "couch_photo_url": "",
    "website_url": "",
    "instagram_url": "",
    "facebook_url": "",
    "auto_reply": "",
    "biography": "",
    "education": "",
    "relevant_links": "",
    "preference": "",
    "profile": "",
    "dealbreaker": "",
    "is_therapist_verified": "0",
};